Update QA automation script (#224)
(cherry picked from commit 6b250fc97e46eee4b9d492080ae2bcc7a29975b6)

diff --git a/tests/qa/run b/tests/qa/run
--- a/tests/qa/run
+++ b/tests/qa/run
@@ -2,6 +2,7 @@
 
 HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 ROOT=$(cd $HERE/../..; pwd)
+READIES=$ROOT/deps/readies
 
 (( VERBOSE > 1 )) && { set -x; PS4='$LINENO: '; }
 
@@ -20,6 +21,7 @@ if [[ $1 == --help || $1 == help ]]; then
 		NOP=1                         Do not execute automation command
 		VERBOSE=N                     Set verbosity level (N=1,2)
 		QUICK=1                       Only test one RS version
+		RS_VERSION=ver                Test for RS version `ver`
 
 		Other configuration:
 		RS_VERSIONS file includes Redis Enterprive versions for release tests.
@@ -28,11 +30,11 @@ if [[ $1 == --help || $1 == help ]]; then
 	exit 0
 fi
 
-if [[ -z $QA_AUTOMATION_USERNAME ]]; then
+if [[ -z $QA_AUTOMATION_USERNAME && $NOP != 1 ]]; then
 	echo "Variable QA_AUTOMATION_USERNAME is undefined." >&2
 	exit 1
 fi
-if [[ -z $QA_AUTOMATION_PASS ]]; then
+if [[ -z $QA_AUTOMATION_PASS && $NOP != 1 ]]; then
 	echo "Variable QA_AUTOMATION_PASS is undefined." >&2
 	exit 1
 fi
@@ -67,11 +69,11 @@ run_test() {
 	cd $HERE
 
 	json_in=$(mktemp /tmp/$TEST.json.XXXX)
-	$ROOT/deps/readies/bin/xtx -e RS_MODULE -e MODULE_VERSION -e RS_VERSION $TEST.json > $json_in
+	$READIES/bin/xtx -e RS_MODULE -e MODULE_VERSION -e RS_VERSION $TEST.json > $json_in
 	(( VERBOSE >= 1 )) && cat $json_in
 
 	if [[ $NOP == 1 ]]; then
-		echo "Testing RS $RS_VERSION"
+		echo "Testing ${RS_MODULE}/${MODULE_VERSION} for RS $RS_VERSION"
 		return 0
 	fi
 
@@ -85,24 +87,28 @@ run_test() {
 	status=$(results .status)
 	if [[ $rc == 0 && $status == success ]]; then
 		id=$(results .data[0])
-		echo "Tests running for RS $RS_VERSION"
+		echo "Tests running on ${RS_MODULE}/${MODULE_VERSION} for RS $RS_VERSION"
 		echo "Results: https://qa-automation-center.redislabs.com/ui#dashboard/flow/$id"
 		return 0
 	else
 		err=$(results .message)
-		echo "Failed to run tests for RS $RS_VERSION: $err"
+		echo "Failed to run tests on ${RS_MODULE}/${MODULE_VERSION} for RS $RS_VERSION: $err"
 		return 1
 	fi
 }
 
 rc=0
-if [[ $QUICK == 1 ]]; then
-	RS_VERSIONS=$(cat $HERE/RS_VERSIONS | head -1)
-else
-	RS_VERSIONS=$(cat $HERE/RS_VERSIONS)
-fi
-for RS_VERSION in $RS_VERSIONS; do
+if [[ ! -z $RS_VERSION ]]; then
 	run_test $RS_VERSION
-	[[ $? != 0 && $rc == 0 ]] && rc=$?
-done
+else
+	if [[ $QUICK == 1 ]]; then
+		RS_VERSIONS=$(cat $HERE/RS_VERSIONS | head -1)
+	else
+		RS_VERSIONS=$(cat $HERE/RS_VERSIONS)
+	fi
+	for RS_VERSION in $RS_VERSIONS; do
+		run_test $RS_VERSION
+		[[ $? != 0 && $rc == 0 ]] && rc=$?
+	done
+fi
 exit $rc
